services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d usersdb" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
     build: .
     depends_on:
       db:
         condition: service_healthy
     environment:
       SPRING_PROFILES_ACTIVE: dev
     ports:
        - "8080:8080"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  dbdata: