server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/usersdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true