server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/userdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
